### ISSUE TITLE
Optimizing Inference Time and Running the Service on GPU?

### ISSUE THREAD

**Issue by IbrarBabar** [JavierCoronel/mosaic_generator#6]
Hi @JavierCoronel, I am currently running the Mosaic Image Generator on a CPU, but the inference time is quite slow—processing a single image takes around 3 to 4 minutes. I would like to know if there are any ways to improve the performance.

Below is the **default.yaml** file I am using:

```
image_path: data/dog.jpg # string with absolute or relative path to the image
output_folder: data/ # string with absolute or relative path to the output folder
edge_extraction_method: HED # string with any of the options: HED (deep learning method), diblasi or sobel
tile_size: 10 # int defining the tile size in pixels
coloring_method: original # str with any of the options: original (more colors), kmeans
num_colors: 5 # int with number of colors to extract, only applicable when coloring_method: kmeans
resize_image: False # bool defining if to resize the image to half the size
mosaic_height: 10 # Size in cm of the desired mosaic
mosaic_width: 10 # Size in cm of the desired mosaic
interactive_edge_modification: False # If set to true it opens an interactive window to modify the edges
save_intermediate_steps: False # Defines if to save the intermediate steps (extracted edges, mosaic guides)
edges_path : null # You can load extracted edges if they were saved, give the path to the image with the edges

hydra:
  run:
    dir: output
```

### My Questions:
1) Is there a way to optimize the inference time using only configuration changes?
2) Would running the service on a GPU significantly improve performance?
- If so, what changes are required to enable GPU acceleration?
- Do we need to modify the code, or can it be done through configuration?
- What dependencies or environment setups are required for GPU support?

I would appreciate any guidance on improving performance, whether through configuration tweaks or enabling GPU processing.

Thanks in advance! 🚀
